version: '3.8'

services:
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
    volumes:
      - ./:/app
  
  web-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}

# docker-compose up  web-prod --build
# docker-compose up  web-dev --build
